config/routes.rb
Rails.application.routes.draw do
  get 'profiles/edit'

  devise_for :users, controllers: { registrations: 'registrations' }

  resources :jobs
  resources :jobs do
    resources :resumes
  end

  namespace :admin do
    resources :jobs do
      member do
        post :publish
        post :hide
      end
      resources :resumes
    end
  end

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
  validates :title, :wage_lower_bound, :wage_upper_bound, :company, :location, :category, presence: true
  validates :wage_lower_bound, numericality: { greater_than: 0 }
  validates :wage_upper_bound, numericality: { greater_than: :wage_lower_bound }

  scope :published, -> { where(is_hidden: false) }
  scope :recent, -> { order('created_at DESC') }

  has_many :resumes

  def publish!
    self.is_hidden = false
    save
  end

  def hide!
    self.is_hidden = true
    save
  end
end

app/models/resume.rb
class Resume < ApplicationRecord
  belongs_to :user
  belongs_to :job

  mount_uploader :attachment, AttachmentUploader

  validates :content, presence: true

  scope :recent, -> {order("created_at DESC")}

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  has_one :profile
  has_many :resumes

  before_create :build_profile

  def admin?
    is_admin
  end
end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_admin_job, only: [:show, :edit, :update, :destroy, :publish, :hide]
  before_action :require_is_admin
  layout "admin"
  def show
  end

  def index
    @jobs = Job.all
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)

    if @job.save
      redirect_to admin_jobs_path, notice: "New job created successfully by admin."
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @job.update(job_params)
      redirect_to admin_jobs_path, notice: "Job updated successfully by admin."
    else
      render :edit
    end
  end

  def destroy
    @job.destroy
    redirect_to admin_jobs_path, warning: "Job deleted successfully by admin."
  end

  def publish
    @job.publish!
    redirect_to :back
  end

  def hide
    @job.hide!
    redirect_to :back
  end

  private

  def set_admin_job
    @job = Job.find(params[:id])
  end

  def job_params
    params.require(:job).permit(:title, :description, :wage_upper_bound, :wage_lower_bound, :company, :location, :category, :contact_email, :is_hidden)
  end

end

app/controllers/admin/resumes_controller.rb
class Admin::ResumesController < ApplicationController
  before_action :authenticate_user!
  before_action :require_is_admin

  layout 'admin'

  def index
    @job = Job.find(params[:job_id])
    @resumes = @job.resumes.recent
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def require_is_admin
    if !current_user.admin?
      flash[:alert] = "You are not admin!"
      redirect_to :back
    end
  end

end

app/controllers/confirmations_controller.rb
# class ConfirmationsController < Devise::ConfirmationsController
#   private
#
#   def after_confirmation_path_for(_resource_name, resource)
#     sign_in(resource)
#     user_path(resource[:id], cp: true)
#   end
# end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @q = Job.published.ransack(params[:q])
    @jobs = @q.result
    #
    # @jobs = case params[:order]
    #         when 'by_lower_bound'
    #           Job.published.order('wage_lower_bound DESC')
    #         when 'by_upper_bound'
    #           Job.published.order('wage_upper_bound DESC')
    #         when 'by_company'
    #           Job.published.order('company ASC')
    #         when 'by_location'
    #           Job.published.order('location ASC')
    #         when 'by_category'
    #           Job.published.order('category ASC')
    #         when 'by_title'
    #           Job.published.order('LOWER(title) ASC')
    #         else
    #           Job.published.recent
    # end
    @jobs = @jobs.paginate(page: params[:page], per_page: 5)
  end

  def show
    if @job.is_hidden
      flash[:warning] = 'Job not available.'
      redirect_to :back
    end
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)
    if @job.save
      redirect_to jobs_path, notice: 'Job was successfully created.'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @job.update(job_params)
      redirect_to jobs_path, notice: 'Job was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @job.destroy
    redirect_to jobs_path, notice: 'Job was successfully destroied.'
  end

  private

  def set_job
    @job = Job.find(params[:id])
  end

  def job_params
    params.require(:job).permit(:title, :description, :wage_upper_bound, :wage_lower_bound, :company, :location, :category, :contact_email, :is_hidden)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def create
    build_resource(sign_up_params)

    if resource.save
      yield resource if block_given?
      if resource.active_for_authentication?
        set_flash_message :notice, :signed_up if is_flashing_format?
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_flashing_format?
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      resource.errors.full_messages.each { |x| flash[x] = x } # Rails 4 simple way
      redirect_to root_path
    end
  end
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :authenticate_user!

  def new
    @job = Job.find(params[:job_id])
    @resume = Resume.new
  end

  def create
    @job = Job.find(params[:job_id])
    @resume = Resume.new(resume_params)
    @resume.job = @job
    @resume.user = current_user

    if @resume.save
      flash[:notice] = "Resume submitted."
    else
      render :new
    end
  end

private
  def resume_params
    params.require(:resume).permit(:content, :attachment)
  end
end

app/helpers/admin/jobs_helper.rb
module Admin::JobsHelper
end

app/helpers/admin/resumes_helper.rb
module Admin::ResumesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
end

  def resource
    @resource ||= User.new
    end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
    end
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice", "warning"
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
  def render_job_status(job)
    if job.is_hidden
      fa_icon "lock lg"
    else
      fa_icon "globe lg"
    end
  end
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/views/admin/jobs/_form.html.erb
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <%= simple_form_for [:admin,@job] do |f| %>
            <%= f.error_notification %>
            <div class="form-inputs">
                <%= f.input :title, placeholder:"Designer" %>
                <%= f.input :description, placeholder: "Experienced Web/Mobile Designer" %>
                <%= f.input :wage_lower_bound, placeholder: "30000" , label: "Min Salary:"%>
                <%= f.input :wage_upper_bound, placeholder: "50000", label: "Max Salary:" %>
                <%= f.input :location, collection:['Houston','Beijing','Shanghai','Shenzhen'], selected:'Houston' %>
                <%= f.input :company, placeholder: 'Your Company' %>
                <%= f.input :category, collection:['Designer','Engineer','Programmer'],selected:'Designer' %>
                <%= f.input :contact_email, placeholder: "example@yourcompany.com"%>
                <%= f.input :is_hidden, label: "Publish", checked_value: false, unchecked_value: true %>
            </div>
            <div class="form-actions">
                <%= f.button :submit %>
            </div>
        <% end %>
    </div>
</div>

app/views/admin/jobs/edit.html.erb
<h1>Admin Editing Job</h1>

<%= render 'form', job: @job %>

app/views/admin/jobs/index.html.erb
<div class="pull-right">
  <%= link_to "New Job", new_admin_job_path, class: "btn btn-primary" %>
</div>
<h1>Jobs</h1>
<div class="table-responsive">
  <table class="table table-hover table-striped">
    <thead>
      <tr>
        <th>Title</th>
        <th>Resume Count</th>
        <th>Min Salary</th>
        <th>Max Salary</th>
        <th colspan="3"></th>
        <th>Post Time</th>
      </tr>
    </thead>

    <tbody>
      <% @jobs.each do |job| %>
        <tr>
          <td>
            <%= render_job_status(job) %>
            <%= link_to job.title, job %>
          </td>
          <td><%= link_to job.resumes.count, admin_job_resumes_path(job) %></td>
          <td><%= job.wage_lower_bound %></td>
          <td><%= job.wage_upper_bound %></td>
          <td><%= link_to 'Edit', edit_admin_job_path(job) %></td>
          <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <td>
            <% if job.is_hidden %>
            <%= link_to "Publish", publish_admin_job_path(job), method: :post, class: "btn btn-success" %>
            <% else %>
            <%= link_to "Hide", hide_admin_job_path(job), method: :post, class: "btn btn-warning" %>
            <% end %>
          </td>
          <td><%= job.created_at.strftime("%D") %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>

app/views/admin/jobs/new.html.erb
<h1>Admin New Job</h1>

<%= render 'form', job: @job %>

app/views/admin/jobs/show.html.erb
<h1><%= @job.title %></h1>

<p>
  <%= simple_format(@job.description) %>
</p>

app/views/admin/resumes/_resume.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="row">
      <div class="col-md-12">
        <h3 class="panel-title">
          <%= resume.user.email %>
        </h3>
      </div>
    </div>
  </div>
  <div class="panel-body">
    <div class="trix-content">
      <p><%= simple_format(resume.content) %></p>

    </div>
    <hr>
    <% if resume.attachment.present? %>
      <%= fa_icon "paperclip" %>
      <%= link_to "Download Resume", resume.attachment_url %>
    <% else %>
      No Attachment
    <% end %>
  </div>
</div>

app/views/admin/resumes/index.html.erb
<h2> <%= @job.title %> - Resume List</h2>

<hr>

<%= render partial: "resume", collection: @resumes, as: :resume %>

app/views/common/_flashes.html.erb
<% if flash.any? %>
    <% user_facing_flashes.each do |key, msg| %>
        <div id="notice_wrapper">
            <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
                <button class="close" data-dismiss="alert">&times;</button>
                <%= msg %>
            </div>
        </div>
    <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer>
    <div class="social">
        <%= fa_icon "facebook" %>
        <%= fa_icon "twitter" %>
        <%= fa_icon "weixin" %>
        <%= fa_icon "github" %>
    </div>
    <p class="text-center">Job Listing © designed by <a href="http://zion.logdown.com">Zion</a></p>
</footer>

app/views/common/_login_modal.html.erb
<div class="modal fade" tabindex="-1" role="dialog" id="login">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Sign in</h4>
            </div>
            <div class="modal-body">
                <%= simple_form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
                    <%= f.input :email %>
                    <%= f.input :password %>
                    <%= f.input :remember_me, :as => :boolean, :label => false, :inline_label => true if devise_mapping.rememberable? %>
                    <%= f.submit "Sign in", class: 'btn btn-small btn-success' %>
                <% end %>
            </div>
            <div class="modal-footer">
                <%= render "devise/shared/links" %>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

app/views/common/_modal.html.erb
<%= render 'common/login_modal' %>
<%= render 'common/sign_up_modal' %>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top" id="navbar">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to "AwesomeTalent", root_path, class:"navbar-brand" %>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <% if !current_user %>
                    <li><%= link_to "Log In", "#login", "data-toggle" => "modal", class: "btn btn-small" %></li>
                    <li><%= link_to "Sign up", "#sign_up","data-toggle" => "modal", class: "btn btn-small" %></li>
                <% else %>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Hi, <%= current_user.email %>
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <% if current_user.admin? %>
                                <li><%= link_to "Admin Panel", admin_jobs_path %></li>
                            <% end %>
                            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete%></li>
                        </ul>
                    </li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>
<%= render "common/modal" %>

app/views/common/_sign_up_modal.html.erb
<div class="modal fade" tabindex="-1" role="dialog" id="sign_up">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Sign up</h4>
            </div>
            <div class="modal-body">
                <%= simple_form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
                    <%= f.input :email %>
                    <%= f.input :password %>
                    <%= f.input :password_confirmation %>
                    <%= f.submit "Sign up", class: 'btn btn-small btn-success' %>
                <% end %>
            </div>
            <div class="modal-footer">
                <%= render "devise/shared/links" %>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

app/views/home/index.html.erb
<section id="banner">
    <div class="wrapper">
        <header>
            <p id="logo">Awe<span>some</span>Talent</p>
            <nav>
                <a href="#">Home</a>
                <a href="#">Jobs</a>
                <a href="#">Talents</a>
                <a href="#">About</a>
            </nav>
        </header>
        <div class="content">
            <h1 class="title">Awesome Talent</h1>
            <h2 class="sub_title">
                We want the best!
                We give the best!
                We are the best!  We want the best!
                  We give the best!
          </h2>
            <p class="button_wrapper">
                <a href="/jobs" class="button button_highlight">Join Us Now</a>
            </p>
        </div>
        <footer class="section-footer">
            <i class="fa fa-angle-double-down" aria-hidden="true"></i>
        </footer>
    </div>
</section>
<section id="services">
    <div class="wrapper">
        <div class="service">
            <h3>Dream Jobs</h3>
            <p>Best place to find your dream jobs. The sky is the limit!</p>
            <button href="#" class="button button_highlight button_small">Learn More</button>
        </div>
        <div class="service middle">
            <h3>Absolute Talents</h3>
            <p>You are in the right place to get the best people. </p>
            <button href="#" class="button button_highlight button_small middle">Learn More</button>
        </div>
        <div class="service">
            <h3>Awe Services</h3>
            <p>We are at your service any time, to make the best meet each other.</p>
            <button href="#" class="button button_highlight button_small">Learn More</button>
        </div>
    </div>
</section>
<section id="how_it_work">
    <h2 class="title">How it works</h2>
    <div id="carousel" class="carousel slide" data-ride="carousel" data-intervel=4500 >
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#carousel" data-slide-to="0" class="active"></li>
            <li data-target="#carousel" data-slide-to="1"></li>
            <li data-target="#carousel" data-slide-to="2"></li>
            <li data-target="#carousel" data-slide-to="3"></li>
        </ol>
        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
            <div class="item active">
                <div class="wrapper">
                    <div class="hiw row " id="for_talents">
                        <div class="step">
                            <h4>Submit Resume</h4>
                            <%= image_tag("application.png") %>
                        </div>
                        <div class="step" >
                            <h4>Get Found</h4>
                            <%= image_tag("people-1.png") %>
                        </div>
                        <div class="step" >
                            <h4>Interviewed</h4>
                            <%= image_tag("business.png") %>
                        </div>
                        <div class="step" >
                            <h4>Get Hired</h4>
                            <%= image_tag("people.png") %>
                        </div>
                    </div>
                </div>
                <div class="carousel-caption">
                    <p>Find the dream job for talents.</p>
                </div>
            </div>
            <div class="item">
                <img src="https://ww1.sinaimg.cn/large/006y8lVagy1fc1b0crrsuj31kw11yajd.jpg" alt="">
                <div class="carousel-caption">
                    <p class="inverse">Through design we redefine beauty.</p>
                </div>
            </div>
            <div class="item">
                <div class="wrapper">
                    <div class="hiw row" id="for_companies">
                        <div class="step">
                            <h4>Post Job</h4>
                            <%= image_tag("signs.png") %>
                        </div>
                        <div class="step">
                            <h4>Get Resumes</h4>
                            <%= image_tag("signature.png") %>
                        </div>
                        <div class="step">
                            <h4>Lock Talents</h4>
                            <%= image_tag("search.png") %>
                        </div>
                    </div>
                </div>
                <div class="carousel-caption">
                    <p>Get the star emplyees for company.</p>
                </div>
            </div>
            <div class="item">
                <img src="https://ww1.sinaimg.cn/large/006tNc79gy1fc3euutxjlj31kw11xqj3.jpg" alt="">
                <div class="carousel-caption">
                    <p class="inverse">Throgh coding we create a new world.</p>
                </div>
            </div>
        </div>
        <!-- Controls -->
        <a class="left carousel-control" href="#carousel" role="button" data-slide="prev"  style="background:none !important">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#carousel" role="button" data-slide="next"  style="background:none !important">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</section>
<section id="testimony">
    <div class="wrapper">
        <h2 class="title"> What our customers say </h2>
        <div class="testimony">
            <%= image_tag("photoes/female-smile-1.jpg") %>
            <p>You won't believe how fast I land on my job through Awesome Talent. It is the no-brainer site to go for dream job.</p>
        </div>
        <div class="testimony">
            <%= image_tag("photoes/man-smile-1.jpg") %>
            <p>I found a really experienced one here, and together we are making some really awesome product.</p>
        </div>
        <div class="testimony">
            <%= image_tag("photoes/female-smile.jpg") %>
            <p>My friend told me she got her first job on AwesomeTalent so I sould give it a try. I am really happy that I did.</p>
        </div>
        <div class="testimony">
            <%= image_tag("photoes/male-smiling.jpg") %>
            <p>I got my intership here last summer. I am graduating soon and I already have mutiple awesome offers.</p>
        </div>
        <a href="#" class="button button_wrapper button_highlight">Act Now</a>
    </div>
</section>

app/views/jobs/_form.html.erb
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <%= simple_form_for(@job) do |f| %>
            <%= f.error_notification %>
            <div class="form-inputs">
                <%= f.input :title, placeholder:"Designer" %>
                <%= f.input :description, placeholder: "Experienced Web/Mobile Designer" %>
                <%= f.input :wage_lower_bound, placeholder: "30000" , label: "Min Salary:"%>
                <%= f.input :wage_upper_bound, placeholder: "50000", label: "Max Salary:" %>
                <%= f.input :location, collection:['Houston','Beijing','Shanghai','Shenzhen'], selected:'Houston' %>
                <%= f.input :company, placeholder: 'Your Company' %>
                <%= f.input :category, collection:['Designer','Engineer','Programmer'],selected:'Designer' %>
                <%= f.input :contact_email, placeholder: "example@yourcompany.com"%>
                <%= f.input :is_hidden, label: "Publish", checked_value: false, unchecked_value: true %>
            </div>
            <div class="form-actions">
                <%= f.button :submit %>
            </div>
        <% end %>
    </div>
</div>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>

app/views/jobs/index.html.erb
<div class="pull-right">
    <!-- <span class="dropdown">
        <%= link_to "#", class: "dropdown-toggle btn btn-info", data:{toggle:"dropdown"} do %>
            Sort_by
    <b class="caret"></b>
        <% end %>
        <ul class="dropdown-menu">
            <li><%= link_to "Sort by Min Wage", jobs_path(order: 'by_lower_bound') %></li>
            <li><%= link_to "Sort by Max Wage", jobs_path(order: 'by_upper_bound') %> </li>
            <li><%= link_to "Sort by Post Time", jobs_path %></li>
        </ul>
    </span> -->
    <div class="search">
        <%= search_form_for @q do |f| %>
            <%= f.label :Search %>
            <%= f.search_field :title_or_description_or_company_or_location_or_category_cont %>
            <%= f.submit %>
        <% end %>
    </div>
    <%= link_to "New Job", new_job_path, class: "btn btn-primary" %>
</div>
<h1>Jobs</h1>
<div class="table-responsive">
    <table class="table table-hover table-striped">
        <thead>
            <tr>
                <th><%= sort_link(@q, :title, "Title", default_order: :asc) %></th>
                <th><%= sort_link(@q, :description, default_order: :asc) %></th>
                <th>Salary</th>
                <th><%= sort_link(@q, :location, default_order: :asc) %></th>
                <th><%= sort_link(@q, :company, default_order: :asc) %></th>
                <th><%= sort_link(@q, :category, default_order: :asc) %></th>
                <th colspan="2"></th>
                <th><%= link_to "Post Time", jobs_path %><span class="fa fa-caret-down"></span></th>
            </tr>
        </thead>
        <tbody>
            <% @jobs.each do |job| %>
                <tr>
                    <td><%= link_to job.title, job %></td>
                    <td><%= job.description %></td>
                    <td><span  class="label label-default"><%= job.wage_lower_bound %> - <%= job.wage_upper_bound %></span></td>
                    <td><%= job.location %></td>
                    <td><%= job.company %></td>
                    <td><%= job.category %></td>
                    <td><%= link_to 'Edit', edit_job_path(job) %></td>
                    <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                    <td><%= job.created_at.strftime("%D") %></td>
                </tr>
            <% end %>
        </tbody>
    </table>
    <div class="apple_pagination">
        <div class="page_info">
            <%= page_entries_info @jobs %>
        </div>
        <%= will_paginate @jobs %>
    </div>
</div>
<br>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form', job: @job %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @job.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= simple_format(@job.description) %>
</p>

<div class="text-center">
  <%= link_to "Upload Resume", new_job_resume_path(@job), :style => "font-size: 30px; text-decoration:underline;" %>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobListingMogai</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'common/navbar' %>
    <%= render 'common/flashes' %>
    <div class="container-fluid">
      <div class="sidebar col-md-2">
        Sidebar
      </div>
      <div class="main col-md-10">
      <%= yield %>
      </div>
    </div>
    <%= render 'common/footer' %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>JobListingMogai</title>
        <%= csrf_meta_tags %>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>
    <body>
        <%= render 'common/navbar' %>
        <%= render 'common/flashes' %>
        <div class="container">
            <div class="row">
                <%= yield %>
            </div>
        </div>
        <%= render 'common/footer' %>
    </body>
</html>

app/views/resumes/create.html.erb
<h1>Resumes#create</h1>
<p>Find me in app/views/resumes/create.html.erb</p>

app/views/resumes/destroy.html.erb
<h1>Resumes#destroy</h1>
<p>Find me in app/views/resumes/destroy.html.erb</p>

app/views/resumes/index.html.erb
<h1>Resumes#index</h1>
<p>Find me in app/views/resumes/index.html.erb</p>

app/views/resumes/new.html.erb
<div class="well">
  <h3>Submit your resume for <%= @job.title %></h3>
  <hr>
  <%= simple_form_for  [@job, @resume], html: { multipart: true } do |f| %>
    <%= f.input :content %>
    <%= f.input :attachment %>

    <%= f.submit "Apply" %>
  <% end %>
</div>